### PR TITLE
Add settings page

### LINKED ISSUE #12: [FEATURE REQUEST] Settings page/more setting variables
I read in a closed issue that you didn't plan to include a settings page for "now" (half a year ago). Did your stance on this change?

I tried using your extension but it clashes with another extension I use ("Unite"). I use Unite to add a Close button into my topbar so I can close windows with a quick wrist flick. It also disables the Window titles. Here is a screenshot with both extensions enabled.

scr

If I use Simple-Task-Bar, the Activities button get hidden (even if I re-enable it in Unite). Window titles will also be shown (which I tried to disable via Unite. I only wanted to see the app name). 

While you added easy-to-edit variables at the top of extension.js, my issue with Window titles doesn't seem to be one an option there. So a dedicated Settings page could help here or at least an additional variable to disable window titles.

If you do decide to add a Settings page (or more variables), here are some ideas:

- add configurable spacing between each workspace section for clearer visibility (e. g. 35 px before the [2] / after the Firefox icon in my screenshot)

- ~shortcuts for window switching within the current workspace (with wraparound) based on the currently focused window. For example: Super+Left/Right or A/D. While people can use Alt/Super+Tab, the order of it is based on recent usage and it shows all apps. So having a non-changing order (like your extension does it) could also be useful and quicker since you don't have to first search for the app in the list of all open apps.~ found an extension which disables listing of all open apps in the Alt+Tab, so this is also kinda obsolete now.

- always show the overview when switching workspaces (and not just when pressing a button on the taskbar), if no app is running on the new workspace. 

- ~disable Window titles and only show app name (or at least not forcing the Window title update)~ pr opened

- ~maybe monochrome icons (since that seems to be GNOME's default look)~ looks kinda bad

------------------------------

It's kinda redundant to have the normal Window title (menu) and your "Line" to indicate the currently focused window. How about merging these 2 (although I don't know how difficult that would be). Here is a mockup of what I mean:

Mockup

[Edit]

BTW do you accept PRs? While I am only looking into learning Gnome extensions right now, adding a variable to disable the window title update seems easy to do even for a beginner.

### PR DESCRIPTION
**Pull request by Leleat**
Closes #12. I also added the 3 options I suggested in #12.

Since I am new to JS and Gnome Extensions you should check the code fairly thoroughly.

I followed these Tutorials:

https://wiki.gnome.org/Projects/GnomeShell/Extensions/Writing#Extension_Preferences
https://www.youtube.com/playlist?list=PLr3kuDAFECjZhW-p56BoVB7SubdUHBVQT (part 7 for the GUI)

The prefs.ui file is created using Glade and is just an xml file.

I moved some functions (those related to the 'Activitites' button and the 'Places' Icon) from the enable()/disable() functions into the Windowlist class and merged them into one to easily toggle them via the settings.

Adding new settings now should be pretty easy.

### CODE REVIEW

**Comment by Leleat** [comment]
For the 'Show overview when no app is running' setting I added a timer so that the animation can still play. Without the timer the animation for the workspace switching will be skipped, if the new workspace has no apps running.

This is a pretty bad solution since I hardcoded a duration which means it doesn't work very well with no/custom animations.

Another thing I wasn't sure of is cleaning up after the timer. In
https://wiki.gnome.org/Projects/GnomeShell/Extensions/TipsOnMemoryManagement#Main_Loop_Sources
they mention having to remove the GSource.

**Comment by fthx** [comment]
Hi,

Thanks ! I don't have any time before tomorrow to check that.
Could you remove all the overview part so we can focus on settings for this PR ? It would be more sound and clear.
You could pull another PR for overview ?

**Comment by Leleat** [comment]
> Could you remove all the overview part so we can focus on settings for this PR ? It would be more sound and clear.

Done, also removed the other 2 settings (padding between workspaces  and only showing app name instead of window title). So now only the settings page is added.

**Comment by fthx** [comment]
Great job !

This works perfectly. Simple and clear UI.
Suggestion : add "(default=20)" after "icon size" and "(0-255, default=127)" after "hidden opacity" and "(default=A,BB,CCC,DDDD)" after "custom ws labels". To help users to revert or to use right syntax.

**Comment by Leleat** [comment]
> add "(default=20)" after "icon size" and "(0-255, default=127)" after "hidden opacity" and "(default=A,BB,CCC,DDDD)" 

I added those as tooltips but I don't mind putting it your suggestion. Do you want me to open a PR? Or do you want to do it  yourself (you just need to edit the prefs.ui file with Glade)?

**Pull request merged**
