### PR TITLE
Add more settings

### PR DESCRIPTION
**Pull request by Leleat**
Add 3 settings:

- show overview, if no app is running on the workspace (i.e. when switching the workspace and there is no app or if the last window is closed on the current workspace)

- padding between workspaces for clearity

- option to show app name instead of full window title

### CODE REVIEW

**Comment by fthx** [comment]
Could you update your extension.js file with my latest commit ?
Could you create another setting ("Monochrome Icons" or something similar in a good English lang.) ? Monochrome is quite nice, imho, but it won't fit to everyone.

There are 4 lines to activate with this setting, there are showed here:
https://github.com/fthx/simple-task-bar/commit/19b7e6bdd695bdf2506d993a5e4f02d390942849

I don't have the time before dinner to check other extensions which do show-overview-when-empty-workspace. Did you do that to catch some tricks? If you think it's ok, I'll push tonight your PR, check that there are no bugs, and push it in GS extensions website.

T H A N K S

**Comment by Leleat** [comment]
> Could you update your extension.js file with my latest commit ?

Will do.

> Could you create another setting ("Monochrome Icons" or something similar in a good English lang.) ?

Sure. Btw did you intentionally jsut desaturate the icons? GNOME usually uses https://wiki.gnome.org/Design/OS/SymbolicIcons for their appmenu. (I don't know how to generate them though).

>  show-overview-when-empty-workspace. Did you do that to catch some tricks? If you think it's ok, I'll push tonight your PR, check that there are no bugs, and push it in GS extensions website.

Without a timer the "change workspace" animation gets skipped and you jump directly into the overview (which IMO felt clunky). Don't merge this PR yet. I'll split this PR and put the overview stuff into its own branch. I'll see if I can find someone to help me with the overview stuff and create a new PR then.

**Comment by Leleat** [comment]
Alright, I added 3 settings:

- desaturated icons
- padding between workspaces
- show window titles (or only the app name)

I'll open a new PR for the overview setting I suggested, if I get it working in a decent manner.

**Comment by fthx** [comment]
Great.
In this way, we have a fully working light extension, without known bugs afaik.
I'll have a look today or this week-end at the overview feature.

Monochrome icons: I simply use original GS's way. Look at here:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/panel.js#L216

**Comment by fthx** [comment]
All seems to be ok now, after this:
https://github.com/fthx/simple-task-bar/commit/e7221c25267ffad80a059a9ef121bc98a46f2729
Simply forgot sticky windows desaturation.

**Comment by fthx** [comment]
Ok, some very minor corrections.
https://github.com/fthx/simple-task-bar/commit/c8ac8fdb91faaeba91cba585120a8fb38829a288
Should be ok to be uploaded ? Tell me !

**Comment by Leleat** [comment]
> c8ac8fd

Typo with 'Desatured'. It's 'Desaturated'. But otherwise I think it looks good.

**Comment by fthx** [comment]
Done!
https://extensions.gnome.org/review/19294

**Comment by fthx** [comment]
I removed the big vertical size issue for padding setting.
I just noticed it was not attended!
In v32.

**Pull request merged**
