### PR TITLE
Use symbolic icons

### LINKED ISSUE #17: Symbolic icons instead of just desaturated icons?
Currently the extension just desaturates all icons (if the setting is enabled) but still uses the icons of the theme. GNOME uses symbolic icons by default and only falls back to the theme icon if there is no symbolic icon (and desaturates it). GNOME applies it via a css file.

Here is a screenshot. The bottom half shows how it is currently. The top half uses symbolic icons (you can see GNOME's default on the appmenu). 

Screenshot from 2020-09-29 11-16-42

Do you want to add it to your extension or do you want to leave it as is?

### PR DESCRIPTION
**Pull request by Leleat**
I also renamed the setting from 'desaturated icons' to 'use-symbolic-icons'.
Closes #17.

### CODE REVIEW

**Comment by fthx** [comment]
Oh I misunderstood.
I was rather ok for another setting "symbolic icons". So this setting would appear here:

```
if (this.settings.get_boolean("desaturated-icons")) {
									if (this.settings.get_boolean("use-symbolic-icons")) {
                                                                                        box.add_style_class_name("icon-mode-symbolic");
                                                                        }

					// desaturate icon in case there is no symbolic icon
					let iconEffect = new Clutter.DesaturateEffect();
					box.add_effect(iconEffect);
				}
```

So this new symbolic-icons setting would have no effect if desaturated icons is not ON. I don't think it would be nice to have colored & symbolic icons side-by-side?

**Comment by Leleat** [comment]
> I was rather ok for another setting "symbolic icons"

Ah, I see.

> I don't think it would be nice to have colored & symbolic icons side-by-side?

The 'colored' icons will be desaturated if there are noy symbolic icons. 

But I can add it as a separate setting as you suggested.

**Comment by fthx** [comment]
Well, what I mean is that we can propose two separate settings.
1) desaturated icons
2) symbolic and desaturated icons
The logic would be one option to turn OFF the other when activated ON, but I don't know how to do that. If it's not easy, we can simply do what I wrote two posts above: if desaturated_setting { if symbolic_setting {turn symbolic} desaturate_icon} .
So the first setting would be useless if second is ON, but that's not a big issue I guess...

**Comment by fthx** [comment]
Maybe 
image
Icons appearance ...................... these three buttons for colored, desaturated, symbolic & desaturated

?

**Comment by Leleat** [comment]
Won't add it... because I am too lazy right now (and since I personally don't use it anyway).

**Pull request closed without merging**
